backends/urls.py
from django.urls import path

from .views import *

app_name = 'vlads_app'

urlpatterns = [
    path('', home, name='home'),
    path('news/', news, name='news'),
    path('accounts/register/', user_signup, name='user_signup'),
    path('accounts/login/', user_login, name='user_login'),
    path('accounts/logout/', user_logout, name='logout'),
    path('services/', service_selection, name='service_selection'),
    path('service/add/', add_service, name='add_service'),
    path('service/<int:service_id>/', day_selection, name='day_selection'),
    path('service/<int:service_id>/day/<int:day_id>/', time_selection, name='time_selection'),
    path('service/<int:service_id>/day/<int:day_id>/add', day_add, name='day_add'),
    path('service/<int:service_id>/day/<int:day_id>/update', day_update, name='day_update'),
    path('service/<int:service_id>/day/<int:day_id>/delete', day_delete, name='day_delete'),
    path('service/<int:service_id>/day/<int:day_id>/time/<int:time_id>/add_customer/', add_customer,
         name='add_customer'),
    path('profile/<int:user_id>/', profile, name='profile'),

]

# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

website/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('backends.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backends/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.core.validators import RegexValidator
from django.db import transaction
from django.forms import TextInput

from .models import Customer, Service

my_validator = RegexValidator("^\+?1?\d{9,12}$",
                              "Phone number must be entered in the format: '+375(29)12-12-123'. Up to 12 digits allowed.")

User = get_user_model()


class UserForm(UserCreationForm):
    email = forms.EmailField(required=True, label='Email')
    first_name = forms.CharField(required=True, label='First Name')
    last_name = forms.CharField(required=True, label='Last Name')

    first_name = forms.CharField(
        label=("Name"),
        widget=forms.PasswordInput(attrs={'class': 'form-control',
                                          'type': 'text',
                                          'required': 'true',
                                          }))

    last_name = forms.CharField(
        label=("Surname"),
        widget=forms.PasswordInput(attrs={'class': 'form-control',
                                          'type': 'text',
                                          'required': 'true',
                                          }))
    username = forms.RegexField(
        label=("Username"), max_length=15, regex=r"^[\w.@+-]+$",
        help_text=("Required. 15 characters or fewer. Letters, digits and "
                   "@/./+/-/_ only."),
        error_messages={
            'invalid': ("This value may contain only letters, numbers and "
                        "@/./+/-/_ characters.")},
        widget=TextInput(attrs={'class': 'form-control',
                                'required': 'true',
                                })
    )

    email = forms.CharField(
        label=("Email"),
        widget=forms.PasswordInput(attrs={'class': 'form-control',
                                          'type': 'text',
                                          'required': 'true',
                                          'placeholder': 'for_example@mail.ru'
                                          }))
    password1 = forms.CharField(
        label=("Password"),
        widget=forms.PasswordInput(attrs={'class': 'form-control',
                                          'required': 'true',
                                          })
    )

    password2 = forms.CharField(
        label=("Password confirmation"),
        widget=forms.PasswordInput(attrs={'class': 'form-control',
                                          'required': 'true',
                                          })
    )

    class Meta:
        model = User
        fields = ("first_name", "last_name", "username", "email", "password1", "password2")


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(
        label=("Username or Email"),
        widget=forms.TextInput(attrs={'class': 'form-control',
                                      'type': 'text',
                                      'required': 'true',
                                      }))
    password = forms.CharField(
        label=("Password"),
        widget=forms.PasswordInput(attrs={'class': 'form-control',
                                          'type': 'password',
                                          'required': 'true',
                                          }))


class ServiceForm(forms.ModelForm):
    name = forms.CharField(
        label=("Name"),
        widget=forms.TextInput(attrs={'class': 'form-control',
                                      'type': 'text',
                                      'required': 'true',
                                      }))

    address = forms.CharField(
        label=("Address"),
        widget=forms.TextInput(attrs={'class': 'form-control',
                                      'type': 'text',
                                      'required': 'true',
                                      }))

    website = forms.CharField(
        label=("URL"),
        widget=forms.URLInput(attrs={'class': 'form-control',
                                     'type': 'text',
                                     'required': 'true',
                                     'placeholder': 'URL'
                                     }))

    email = forms.CharField(
        label=("Email"),
        widget=forms.EmailInput(attrs={'class': 'form-control',
                                       'type': 'text',
                                       'required': 'true',
                                       'placeholder': 'for_example@mail.ru'
                                       }))

    working_days = forms.CharField(
        label=("Working Days"),
        widget=forms.TextInput(attrs={'class': 'form-control',
                                      'type': 'text',
                                      'required': 'true',
                                      }))

    opening_time = forms.TimeField(input_formats=['%H:%M'],
                                   label=("Opening Time"),
                                   widget=forms.TimeInput(attrs={'class': 'form-control', }))

    closing_time = forms.TimeField(input_formats=['%H:%M'],
                                   label=("Closing Time"),
                                   widget=forms.TimeInput(attrs={'class': 'form-control', }))

    phone_number = forms.CharField(
        label=("Phone number"),
        widget=forms.TextInput(attrs={'class': 'form-control',
                                      'type': 'text',
                                      'required': 'true',
                                      }),
        validators=[
            RegexValidator(
                "^\+?375?\(?\d{2}\)\d{7}$",
                message="Phone number must be entered in the format: '+375(29)1234567'"
            )
        ])

    class Meta:
        model = Service
        fields = (
            'name', 'address', 'website', 'email', 'working_days', 'opening_time', 'closing_time',
            'phone_number')

    def __init__(self, *args, **kwargs):
        self._user = kwargs.pop('user')
        self._recording_time = kwargs.pop('recording_time')
        self._working_days = kwargs.pop('working_days')
        super(ServiceForm, self).__init__(*args, **kwargs)

    @transaction.atomic
    def save(self, commit=True):
        service = super(ServiceForm, self).save(commit=False)
        service.owner = self._user

        if commit:
            service.save()

        service.recording_time.add(self._recording_time)

        for day in self._working_days:
            service.working_days.add(day)

        return service.id


class CustomerForm(forms.ModelForm):
    surname = forms.CharField(
        label=("Surname"),
        widget=forms.TextInput(attrs={'class': 'form-control',
                                      'type': 'text',
                                      'required': 'true',
                                      }))

    name = forms.CharField(
        label=("Name"),
        widget=forms.TextInput(attrs={'class': 'form-control',
                                      'type': 'text',
                                      'required': 'true',
                                      }))

    patronymic = forms.CharField(
        label=("Patronymic"),
        widget=forms.TextInput(attrs={'class': 'form-control',
                                      'type': 'text',
                                      'required': 'true',
                                      }))

    car = forms.CharField(
        label=("Car"),
        widget=forms.TextInput(attrs={'class': 'form-control',
                                      'type': 'text',
                                      'required': 'true',
                                      }))

    phone_number = forms.CharField(
        label=("Phone number"),
        widget=forms.TextInput(attrs={'class': 'form-control',
                                      'type': 'text',
                                      'required': 'true',
                                      'placeholder': "Phone number must be entered in the format: '+375(29)1234567'"
                                      }),
        validators=[
            RegexValidator(
                "^\+?375?\(?\d{2}\)\d{7}$",
                message="Phone number must be entered in the format: '+375(29)1234567'"
            )
        ])

    email = forms.EmailField(
        label=("Email"),
        widget=forms.EmailInput(attrs={'class': 'form-control',
                                       'type': 'text',
                                       'required': 'true',
                                       }))

    class Meta:
        model = Customer
        fields = ('surname', 'name', 'patronymic', 'car', 'phone_number', 'email')


class CreateDay(forms.Form):
    recording_time = forms.TimeField(input_formats=['%H:%M'],
                                     label=("Opening Time"),
                                     widget=forms.TimeInput(attrs={'class': 'form-control', }))

    opening_time = forms.TimeField(input_formats=['%H:%M'],
                                   label=("Opening Time"),
                                   widget=forms.TimeInput(attrs={'class': 'form-control', }))

    closing_time = forms.TimeField(input_formats=['%H:%M'],
                                   label=("Closing Time"),
                                   widget=forms.TimeInput(attrs={'class': 'form-control', }))

templates/add_customer.html
{% extends "base.html" %}
{% block title %}
CarService - Сar service record
{% endblock %}

{% block content %}

<div class="container-xl" xmlns="http://www.w3.org/1999/html">
    <div class="card-text mb-4 mt-4">
        <h4>To leave a request you need to provide your contact information: </h4>
        <form action="." method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary col-md-4">Create</button>
        </form>
    </div>
</div>

{% endblock %}

templates/add_service.html
{% extends "base.html" %}

{% block title %}
CarService - Add Service
{% endblock %}

{% block content %}

<div class="container-xl" xmlns="http://www.w3.org/1999/html">
    <div class="container-sm">
        <div class="card mb-4 mt-4">
            <div class="card-body">
                <form action="." method="POST">
                    {% csrf_token %}
                    <div class="container">
                        <div class="card-text mt-3">
                            <h3>Add AutoService:</h3>
                        </div>

                        <div class="card-text ">
                            <label for="id_name">Name:</label>
                            <input type="text" class="form-control" id="id_name" name="name"
                                   placeholder="Diagnostic station No. 1 - Autocentre 'MyService'">
                        </div>

                        <div class="card-text mt-3">
                            <label for="id_address">Address:</label>
                            <input type="text" class="form-control" id="id_address" name="address"
                                   placeholder="Minsk, street Pobedy 25/1">
                        </div>

                        <div class="card-text mt-3">
                            <label for="id_website">Website:</label>
                            <input type="url" class="form-control" id="id_website" name="website"
                                   placeholder="https://www.your_autoservice.com/">
                        </div>

                        <div class="card-text mt-3">
                            <div class="row">
                                <div class="col">
                                    <label for="id_working_days">Working days:</label>
                                    <select class="js-working_days form-control" name="working_days"
                                            multiple="multiple"
                                            id="id_working_days">
                                        {% for day in days %}
                                        <option value="{{ day.pk }}">{{ day.day }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <div class="col">
                                    <label for="id_recording_time">Recording time:</label>
                                    <select class="js-recording_time form-control" name="recording_time"
                                            id="id_recording_time">
                                        {% for recording_time in recording_times %}
                                        <option value="{{ recording_time.id }}">{{ recording_time }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <div class="col">
                                    <label for="id_opening_time">Opening time:</label>
                                    <input type="text" class="form-control" id="id_opening_time" name="opening_time"
                                           placeholder="janem">
                                </div>
                                <div class="col">
                                    <label for="id_closing_time">Closing time:</label>
                                    <input type="text" class="form-control" id="id_closing_time" name="closing_time"
                                           placeholder="janem">
                                </div>
                            </div>
                        </div>

                        <div class="card-text mt-3">
                            <label for="id_email">Service Email:</label>
                            <input type="email" class="form-control" id="id_email" name="email"
                                   placeholder="example@mail.ru">
                        </div>

                        <div class="card-text mt-3">
                            <label for="id_phone_number">Service Phone number:</label>
                            <input type="text" class="form-control" id="id_phone_number" name="phone_number"
                                   placeholder="Phone number must be entered in the format: +375(29)1212123">
                        </div>
                        <div class="card-text mt-3">
                            <button type="submit" class="btn btn-primary col-md-4">Add Autoservice</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $('.js-working_days').select2({
            width: '100%'
        });

        // $(".js-example-responsive").select2({});

        $(".js-example-placeholder-single").select2({
            minimumResultsForSearch: Infinity,
            width: '100%',
        });
    });

    $(function () {
        $("#id_opening_time").timepicker({
            timeFormat: 'HH:mm',
            ampm: false,
            interval: 60,
            minTime: '5',
            maxTime: '11:00pm',
            defaultTime: '8',
            startTime: '05:00',
            dynamic: false,
            dropdown: true,
            scrollbar: true
        });
        $("#id_closing_time").timepicker({
            timeFormat: 'HH:mm',
            ampm: false,
            interval: 60,
            minTime: '5',
            maxTime: '11:00pm',
            defaultTime: '20',
            startTime: '05:00',
            dynamic: false,
            dropdown: true,
            scrollbar: true
        });
    });
</script>
<style>
    p {
        color: red;
    }

    .text {
        font-size: 24px;
    }
</style>
{% endblock %}

templates/day_selection.html
{% extends "base.html" %}

{% block title %}
CarService - {{ service.name }}
{% endblock %}

{% block content %}

<div class="container-xl">
    <div class="card-text mb-4 mt-2">
        <div class="card-body">
            <div class="card-body" style="margin-left: 50px; margin-right: 50px;">
                <div class="container">
                    <div class="card-body" style="width: 550px;">
                        <h4 style="font-weight: normal;"><strong>{{ service.name }}</strong></h4>
                    </div>
                    <div class="row">
                        <div class="col-auto">
                            <div class="card-body" style="margin-top: 20px;">
                                <h5 style="font-weight: normal;">{{ service.address }}</h5>
                            </div>
                        </div>
                        <div class="col-auto" style="margin-left: 40px; margin-top: 20px;">
                            <div class="card-body">
                                <h5 style="font-weight: normal;"><strong>Schedule:</strong></h5>
                            </div>
                            <div class="card-body" >
                            <h6 style="font-weight: normal;">
                                {% for work_day in service.working_days.all %}
                                <strong>{{ work_day }}</strong>
                                {% endfor %}
                                : {{ service.opening_time }} - {{ service.closing_time }}</h6>
                            </div>
                        </div>
                        <div class="col-auto" style="margin-left: 40px; margin-top: 20px;">
                            <div class="card-body">
                                <h5 style="font-weight: normal;"><strong>Contact details:</strong></h5>
                            </div>
                            <div class="card-body">
                                <h6 style="font-weight: normal;">{{ service.phone_number }}</h6>
                            </div>
                            <div class="card-body">
                                <h6 style="font-weight: normal;">{{ service.email }}</h6>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container px-5">
                <div class="container px-5">
                    <div class="container px-5">
                        <div class="card-text mt-2" style="margin-right: 50px; margin-bottom: -20px;">
                            <div class="row">
                                <table class="table table-bordered " style="border-color: #B4B4B4">
                                    <thead>
                                    <tr>
                                        <th scope="col">
                                            <div align="center">&ensp;Mon &ensp;</div>
                                        </th>
                                        <th scope="col">
                                            <div align="center">&ensp;Tue &ensp;</div>
                                        </th>
                                        <th scope="col">
                                            <div align="center">&ensp;Wed &ensp;</div>
                                        </th>
                                        <th scope="col">
                                            <div align="center">&ensp;Thu &ensp;</div>
                                        </th>
                                        <th scope="col">
                                            <div align="center">&ensp;Fri &ensp;</div>
                                        </th>
                                        <th scope="col">
                                            <div align="center">&ensp;Sat &ensp;</div>
                                        </th>
                                        <th scope="col">
                                            <div align="center">&ensp;Sun &ensp;</div>
                                        </th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        {% for week in text_calendar %}
                                        {% for day in week %}
                                        {% if day != 0 %}

                                            {% if day not in work_days %}
                                                {% if request.user.id == service.owner_id or request.user.is_staff %}
                                                <td class="table-active">
                                                    <div class="card-text mb-1 mt-1" align="center">
                                                        <a href="{% url 'vlads_app:day_update' service.id day %}"
                                                           role="button"
                                                           style="text-decoration: none;"><h5 style="font-weight: normal;">{{ day }}</h5></a>
                                                    </div>
                                                </td>
                                                {% else %}
                                                <td class="table-active">
                                                    <div class="card-text mb-1 mt-1" align="center">
                                                        <h5 style="font-weight: normal;">{{ day }}</h5>
                                                    </div>
                                                </td>
                                                {% endif %}
                                            {% else %}
                                                <td>
                                                    <div class="card-text mb-1 mt-1" align="center">
                                                        <a href="{% url 'vlads_app:time_selection' service.id day %}"
                                                           role="button"
                                                           style="text-decoration: none;"><h5 style="font-weight: normal;">{{ day }}</h5></a>
                                                    </div>
                                                </td>
                                            {% endif %}
                                        {% else %}
                                        <td class="table-active"></td>
                                        {% endif %}
                                        {% endfor %}
                                    </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/time_selection.html
{% extends "base.html" %}
{% block title %}
    CarService - {{ service.name }}
{% endblock %}

{% block content %}

    <div class="container-xl" xmlns="http://www.w3.org/1999/html">
        <div class="card-text mb-4 mt-2">
            <div class="card-body">
                <div class="card-body" style="margin-left: 50px; margin-right: 50px;">
                    <div class="container">
                        <div class="card-body" style="width: 550px;">
                            <h4 style="font-weight: normal;"><strong>{{ service.name }}</strong></h4>
                        </div>
                        <div class="row">
                            <div class="col-auto">
                                <div class="card-body">
                                    <h5 style="font-weight: normal;">{{ service.address }}</h5>
                                </div>
                            </div>
                            <div class="col-auto" style="margin-left: 40px;">
                                <div class="card-body">
                                    <h5 style="font-weight: normal;"><strong>Schedule:</strong></h5>
                                </div>
                                <div class="card-body">
                                    <h6 style="font-weight: normal;">
                                        {% for work_day in service.working_days.all %}
                                            <strong>{{ work_day }}</strong>
                                        {% endfor %}
                                        : {{ service.opening_time }} - {{ service.closing_time }}</h6>
                                </div>
                            </div>
                            <div class="col-auto" style="margin-left: 40px;">
                                <div class="card-body">
                                    <h5 style="font-weight: normal;"><strong>Contact details:</strong></h5>
                                </div>
                                <div class="card-body">
                                    <h6 style="font-weight: normal;">{{ service.phone_number }}</h6>
                                </div>
                                <div class="card-body">
                                    <h6 style="font-weight: normal;">{{ service.email }}</h6>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="card-text mb-4 mt-4" style="margin-left: 50px; margin-right: 50px;">
                    {% if times %}
                        <h6>Choose a convenient time for you: </h6>
                        {% for time in times %}
                            <div class="d-inline-block p-2 m-2 ">
                                <a href="{% url 'vlads_app:add_customer' service.id day.id time.id %}" role="button"
                                   style="text-decoration: none;">
                                    <button type="button"
                                            class="btn btn-secondary">{{ time.time|date:"H:i" }}</button>
                                </a>
                            </div>
                        {% endfor %}
                        {% if request.user.id == service.owner_id %}
                            <div class="card-text mb-4 mt-4">
                                <h6>Choose the action you would like to take: </h6>
                                <a href="{% url 'vlads_app:day_delete' service.id day.id %}" role="button"
                                   style="text-decoration: none;">
                                    <button type="button" class="btn btn-danger">Remove a day from work</button>
                                </a>
                            </div>
                        {% endif %}
                    {% else %}
                        <h6>Choose the action you would like to take: </h6>
                        <form action="{% url 'vlads_app:day_update' service.id day %}" method="POST">
                            {% csrf_token %}
                            <div class="card-text mb-2 mt-2">
                                <label for="id_recording_time">Recording time:</label>
                                <select class="js-recording_time form-control" name="recording_time"
                                        id="id_recording_time">
                                    {% for recording_time in recording_times %}
                                        <option value="{{ recording_time }}">{{ recording_time }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="card-text mb-2 mt-2">
                                <label for="id_opening_time">Opening time:</label>
                                <input type="text" class="form-control" id="id_opening_time" name="opening_time"
                                       placeholder="janem">
                            </div>
                            <div class="card-text mb-2 mt-2">
                                <label for="id_closing_time">Closing time:</label>
                                <input type="text" class="form-control" id="id_closing_time" name="closing_time"
                                       placeholder="janem">
                            </div>
                            <button type="submit" class="btn btn-danger">Add a day as a working day</button>

                        </form>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <script>
        $(function () {
            $("#id_opening_time").timepicker({
                timeFormat: 'HH:mm',
                ampm: false,
                interval: 60,
                minTime: '5',
                maxTime: '11:00pm',
                defaultTime: '8',
                startTime: '05:00',
                dynamic: false,
                dropdown: true,
                scrollbar: true
            });
            $("#id_closing_time").timepicker({
                timeFormat: 'HH:mm',
                ampm: false,
                interval: 60,
                minTime: '5',
                maxTime: '11:00pm',
                defaultTime: '20',
                startTime: '05:00',
                dynamic: false,
                dropdown: true,
                scrollbar: true
            });
        });
    </script>

{% endblock %}